image: Visual Studio 2022

version: 'Build {build}'

configuration:
    - Release

test_script:
    - cmd: dotnet test "Simple AVS Generator.Core.Tests\Simple AVS Generator.Core.Tests.csproj"

before_build:
    - cmd: cmake -G "Visual Studio 17" -S . -B "build" -DAPPVEYOR_CI=ON
    - cmd: set /p version=<"version.txt"
    - cmd: appveyor UpdateBuild -Version "v%version%"

build_script:
    - cmd: build.cmd

artifacts:
    - path: "publish/Simple AVS Generator.exe"