image: Visual Studio 2022

version: 'Build {build}'

before_build:
    - cmd: cmake -G "Visual Studio 17" -S . -B "build" -DAPPVEYOR_CI=ON
    - cmd: set /p version=<"version.txt"
    - cmd: appveyor UpdateBuild -Version "v%version%"

build_script:
    - cmd: build.cmd

test_script:
    - cmd: dotnet test -c Debug "SimpleAVSGeneratorCore.Tests\SimpleAVSGeneratorCore.Tests.csproj"

artifacts:
    - path: "publish\\Simple AVS Generator.exe"