image: Visual Studio 2019

version: '{build}'

configuration:
    - Release

before_build:
    - cmd: cmake -G "Visual Studio 16" -S "source" -B "build"

build:
    project: "build/SimpleAVSGenerator.sln"
    verbosity: minimal


artifacts:
    - path: "build/Release/Simple AVS Generator.exe"